### PR TITLE
🐛 fix: key's ending after placeholders is not matched

### PR DESCRIPTION
**Pull request by niqzart**
Hi! I'd like to use this lib in one of my projects, but the bug I in #160 does not allow me to do so. This PR hopefully fixes it. Let me know if any fixes (version bump?) are needed here

### CODE REVIEW

**Comment by niqzart** [comment]
Also pipelines failed because of something unrelated to my changes, I could also try to fix those, if you need me to

**Comment by dukkee** [comment]
Hi @niqzart Thank you for the contribution, I will review it soon 🙏 No worries, I was planning to fix the CI for @boardpack for a whole in the near time

**Comment by dukkee** [comment]
Hi @niqzart Please rebase on master and CI checks should be fine

**Comment by niqzart** [comment]
Hi! Rebase is done. Sure, I've added a simple test for this case, does it look ok?

**Comment by dukkee** [comment]
> Hi! Rebase is done. Sure, I've added a simple test for this case, does it look ok?

Yes, it's fine. Thanks!

**Pull request merged**
