### PR TITLE
fixed list index out of range

### PR DESCRIPTION
**Pull request by hellokaton**
This error is triggered when the length of `len(groups) == 2`.

### CODE REVIEW

**Comment by dukkee** [comment]
Hello, @biezhi Thank you very much for your contribution. One little additional thing. Could you please add test(s) for this case?

**Comment by biezhi** [comment]
> Hello, @biezhi Thank you very much for your contribution. One little additional thing. Could you please add test(s) for this case?

Okay, I will add the unit test later and then push.😊

**Comment by dukkee** [comment]
> Okay, I will add the test case later and then push. :blush:

Great, thanks a lot

**Comment by dukkee** [comment]
Hey @hellokaton, sorry for the delay, I'm ill a bit now. As I see, your fix breaks other tests, hope I will check it soon, it will depend on my health

**Comment by hellokaton** [comment]
@dukkee Health is very important, wish you a speedy recovery. I resubmitted a PR, which can be reviewed when there is time.

**Pull request closed without merging**
