### PR TITLE
✨ add pydantic v2 support for getting error strings

### PR DESCRIPTION
**Pull request by farbodp**

### CODE REVIEW

**Comment by dukkee** [comment]
Hello @farbodp Thank you for your contribution, please don't forget to remove the restriction for the test dependencies here:
https://github.com/boardpack/pydantic-i18n/blob/master/pyproject.toml#L46

**Comment by farbodp** [comment]
Hi @dukkee ,
Thank you for your help. I fixed it, but it seems that I need to work on the tests for v2 compatibility. I will continue fixing them in the following days.

**Comment by dukkee** [comment]
> Hi @dukkee , Thank you for your help. I fixed it, but it seems that I need to work on the tests for v2 compatibility. I will continue fixing them in the following days.

Cool thanks. Once it will be merged, I will prepare a release

**Comment by dukkee** [comment]
Hey @farbodp I fixed the tests in #213 so the actual one will be closed

**Pull request closed without merging**
